# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InventoryService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import inventoryModel_pb2 as inventoryModel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16InventoryService.proto\x12\x0finventorySystem\x1a\x14inventoryModel.proto\"X\n\x11\x43reateBookRequest\x12\x31\n\rbookedCreated\x18\x01 \x01(\x0b\x32\x15.inventorySystem.BookH\x00\x88\x01\x01\x42\x10\n\x0e_bookedCreated\"X\n\x0f\x43reateBookReply\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x31\n\x08response\x18\x02 \x01(\x0b\x32\x1f.inventorySystem.ResponseStatus\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"\x92\x01\n\x0cGetBookReply\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x16\n\x0ereponseMessage\x18\x02 \x01(\t\x12#\n\x04\x62ook\x18\x03 \x01(\x0b\x32\x15.inventorySystem.Book\x12\x31\n\x08response\x18\x04 \x01(\x0b\x32\x1f.inventorySystem.ResponseStatus2\xb5\x01\n\x10InventoryService\x12T\n\nCreateBook\x12\".inventorySystem.CreateBookRequest\x1a .inventorySystem.CreateBookReply\"\x00\x12K\n\x07GetBook\x12\x1f.inventorySystem.GetBookRequest\x1a\x1d.inventorySystem.GetBookReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InventoryService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=65
  _CREATEBOOKREQUEST._serialized_end=153
  _CREATEBOOKREPLY._serialized_start=155
  _CREATEBOOKREPLY._serialized_end=243
  _GETBOOKREQUEST._serialized_start=245
  _GETBOOKREQUEST._serialized_end=275
  _GETBOOKREPLY._serialized_start=278
  _GETBOOKREPLY._serialized_end=424
  _INVENTORYSERVICE._serialized_start=427
  _INVENTORYSERVICE._serialized_end=608
# @@protoc_insertion_point(module_scope)
