# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryModel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14inventoryModel.proto\x12\x0finventorySystem\"\xc8\x01\n\x04\x42ook\x12\x11\n\x04isbn\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12*\n\x05genre\x18\x04 \x01(\x0e\x32\x16.inventorySystem.GenreH\x03\x88\x01\x01\x12\x1c\n\x0fpublishing_year\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x07\n\x05_isbnB\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x12\n\x10_publishing_year\"\xb0\x01\n\rInventoryItem\x12\x1d\n\x10inventory_number\x18\x01 \x01(\x05H\x01\x88\x01\x01\x12%\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x15.inventorySystem.BookH\x00\x12\x31\n\x06status\x18\x03 \x01(\x0e\x32\x1c.inventorySystem.IssueStatusH\x02\x88\x01\x01\x42\x06\n\x04itemB\x13\n\x11_inventory_numberB\t\n\x07_status\"N\n\x0eResponseStatus\x12\x11\n\x04\x63ode\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_codeB\n\n\x08_message*3\n\x05Genre\x12\x0b\n\x07ROMANCE\x10\x00\x12\x0f\n\x0bNON_FICTION\x10\x01\x12\x0c\n\x08THRILLER\x10\x02*\'\n\x0bIssueStatus\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryModel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=503
  _GENRE._serialized_end=554
  _ISSUESTATUS._serialized_start=556
  _ISSUESTATUS._serialized_end=595
  _BOOK._serialized_start=42
  _BOOK._serialized_end=242
  _INVENTORYITEM._serialized_start=245
  _INVENTORYITEM._serialized_end=421
  _RESPONSESTATUS._serialized_start=423
  _RESPONSESTATUS._serialized_end=501
# @@protoc_insertion_point(module_scope)
